stages:
  - test
  - build

tests:
  image: node
  stage: test
  script:
    - npm install
    - npm run webpack
    - npm run lint
    #- npm run test

build:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME .
    - docker push registry.gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
    - curl -X POST -F token=f8965878a557a9f5a0cff58c5bea86 -F ref=master https://gitlab.com/api/v3/projects/1856114/trigger/builds
