image: docker:latest
services:
  - docker:dind

stages:
  - build
  - test
  - release
  - deploy

variables:
  DOCKER_DRIVER: overlay
  BUILD_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  PRODUCTION_REGISTRY: registry.heroku.com
  PRODUCTION_IMAGE: $PRODUCTION_REGISTRY/audeets/web

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull -t $BUILD_IMAGE .
    - docker push $BUILD_IMAGE

linting:
  stage: test
  variables:
    GIT_STRATEGY: none
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $BUILD_IMAGE
    - docker run $BUILD_IMAGE npm run lint

registry:
  stage: release
  variables:
    GIT_STRATEGY: none
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $BUILD_IMAGE
    - docker tag $BUILD_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  only:
    - master

# staging:
#   stage: deploy
#   environment: staging
#   image: cdrx/rancher-gitlab-deploy
#   variables:
#     GIT_STRATEGY: none
#   script:
#     - upgrade --stack $CI_PROJECT_NAMESPACE-staging --wait-for-upgrade-to-finish --no-start-before-stopping --finish-upgrade
#     - curl --header 'Access-Token:o.FJG6cnUeuNLWvQYh3oQJwqeGI6ahd7Xs' --header 'Content-Type:application/json' --data-binary '{"body":"www deployed to staging","title":"audeets.com","type":"note"}' --request POST https://api.pushbullet.com/v2/pushes
#   only:
#     - master

production:
  stage: deploy
  environment: production
  variables:
    GIT_STRATEGY: none
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $RELEASE_IMAGE
    - docker tag $RELEASE_IMAGE $PRODUCTION_IMAGE
    - docker login -u="$GITLAB_USER_EMAIL" -p="$HEROKU_API_KEY" $PRODUCTION_REGISTRY
    - docker push $PRODUCTION_IMAGE
    - "curl -X POST -F token=23a06728ce7e7f8a8aefe25aa7b13a -F ref=REF_NAME https://gitlab.com/api/v4/projects/1687415/trigger/pipeline"
    # - curl --header 'Access-Token:o.FJG6cnUeuNLWvQYh3oQJwqeGI6ahd7Xs' --header 'Content-Type:application/json' --data-binary '{"body":"www deployed to production","title":"audeets.com","type":"note"}' --request POST https://api.pushbullet.com/v2/pushes
  only:
    - master
