version: '2'
services:
  www:
    image: registry.gitlab.com/benoit.quette/web-audits
    container_name: wa-www
    command: npm run start:www:prod
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - elk
      - mongo
    volume:
      - /home/deploy/config:/usr/src/app/config
  audit-gpsi:
    image: registry.gitlab.com/benoit.quette/web-audits
    container_name: wa-audit-gpsi
    command: npm run start:gpsi
    restart: always
    depends_on:
      - rabbitmq
      - elk
    volume:
      - /home/deploy/config:/usr/src/app/config
  audit-seobasic:
    image: registry.gitlab.com/benoit.quette/web-audits
    container_name: wa-audit-seobasic
    command: npm run start:seobasic
    restart: always
    depends_on:
      - rabbitmq
      - elk
    volume:
      - /home/deploy/config:/usr/src/app/config
  store-mongo:
    image: registry.gitlab.com/benoit.quette/web-audits
    container_name: wa-store-mongo
    command: npm run start:mongo
    restart: always
    depends_on:
      - rabbitmq
      - mongo
      - elk
    volume:
      - /home/deploy/config:/usr/src/app/config
  crawl:
    image: registry.gitlab.com/benoit.quette/web-audits
    container_name: wa-crawl
    command: npm run start:crawl
    restart: always
    depends_on:
      - rabbitmq
      - elk
    volume:
      - /home/deploy/config:/usr/src/app/config
  mongo:
    image: mongo:3.3.6
    container_name: wa-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongo:/data/db
      - /etc/mongo:/data/configdb
  rabbitmq:
    image: rabbitmq:3.6-management
    container_name: wa-rabbitmq
    restart: always
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672 # Node port
      - 15671:15671
      - 15672:15672 # Management interface
      - 25672:25672
  elk:
    image: sebp/elk
    container_name: wa-elk
    restart: always
    ports:
      - 5601:5601 # Kibana web interface
      - 9201:9200 # ES JSON interface
      - 5044:5044 # Logstash Beats interface
      - 5001:5000 # Logstash Lumberjack interface
  elastic-search:
    image: elasticsearch:2
    container_name: wa-elastic-search
    restart: always
    ports:
      - 9200:9200
      - 9300:9300

